###############################################################################
#                          Generated on _docker.io                          #
###############################################################################
version: '3.1'
services:
    db:
        image: mysql:8.0
        container_name: iasteroid_db
        restart: always
        volumes:
            - './_databases/db:/var/lib/mysql'
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: near_earth_object
            MYSQL_USER: user
            MYSQL_PASSWORD: 7775
        ports:
                - "16306:3306"
        command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
        networks:
            - default

    webserver:
        image: 'nginx:alpine'
        container_name: iasteroid_nginx
        restart: always
        working_dir: /application
        volumes:
            - '.:/application'
            - './_docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '80:80'
        networks:
            - default

    app:
        build: _docker/php-fpm
        container_name: iasteroid_app
        restart: always
        working_dir: /application
        volumes:
            - '.:/application'
            - './_docker/php-fpm/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini'
        networks:
            - default

    phpmyadmin:
        image: 'phpmyadmin/phpmyadmin'
        container_name: iasteroid_phpmyadmin
        restart: unless-stopped
        ports:
            - 127.0.0.1:8080:80
        links:
            - db
        environment:
            - PMA_HOST=db
            - MYSQL_ROOT_PASSWORD=root
        networks:
            - default
